# Generated by Django 5.2.7 on 2025-11-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('fashion', 'Fashion & Beauty'), ('food', 'Food & Beverage'), ('finance', 'Finance'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=20)),
                ('campaign_budget', models.CharField(choices=[('small', '$1,000 - $5,000'), ('medium', '$5,000 - $15,000'), ('large', '$15,000 - $50,000'), ('enterprise', '$50,000+')], max_length=20)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('social_media_handle', models.CharField(max_length=100)),
                ('primary_platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'Twitter')], max_length=20)),
                ('follower_count', models.IntegerField()),
                ('content_niche', models.CharField(choices=[('fashion', 'Fashion & Beauty'), ('tech', 'Technology'), ('food', 'Food & Lifestyle'), ('business', 'Business & Entrepreneurship'), ('entertainment', 'Entertainment')], max_length=20)),
                ('about', models.TextField()),
            ],
        ),
    ]
