# Generated by Django 5.2.7 on 2025-11-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeynoteSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='speakers/')),
                ('followers', models.CharField(max_length=50)),
            ],
        ),
    ]
