# Generated by Django 5.2.7 on 2025-11-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmisapp', '0002_keynotespeaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('fashion', 'Fashion'), ('food', 'Food & Beverage'), ('finance', 'Finance')], max_length=20)),
            ],
        ),
    ]
