# Generated by Django 5.2.7 on 2025-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmisapp', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='featured_images/')),
            ],
        ),
    ]
